In [1]:
import numpy as np
import math
import random
from cobra import Reaction
import escher
import escher.urls
import cobra
import cobra.test
import json
import os
from IPython.display import HTML
model = cobra.io.load_matlab_model('/Users/LAURENCE/Desktop/Senior Design/RECON1', 'RECON1')

cobra/io/__init__.py:17 UserWarning: cobra.io.sbml requires libsbml
cobra/io/mat.py:136 FutureWarning: elementwise == comparison failed and returning scalar instead; this will raise an error or perform elementwise comparison in the future.


In [2]:
#creat ethanalamine demand
#metabolite is etha_c

DM_etha_c = Reaction('DM_etha_c')
DM_etha_c.name = DM_etha_c

etha_c = model.metabolites.get_by_id('etha_c')

DM_etha_c.add_metabolites({etha_c: -1})
model.add_reaction(DM_etha_c)

#create a transporter for this

Tyr_ggnt = Reaction('Tyr_ggnt')
Tyr_ggnt.name = Tyr_ggnt

Tyr_ggn_e = model.metabolites.get_by_id('Tyr_ggn_e')
Tyr_ggn_c = model.metabolites.get_by_id('Tyr_ggn_c')

Tyr_ggnt.add_metabolites({Tyr_ggn_e: -1, Tyr_ggn_c: 1})
model.add_reaction(Tyr_ggnt)

DM_etha_c.lower_bound = -1
Tyr_ggnt.lower_bound = -1000

except_EX_names = '''DM_etha_c, EX_peplys_e, EX_Tyr_ggn_e, EX_arg__L_e, EX_asn__L_e, EX_asp__L_e, EX_chol_e, EX_cl_e, EX_glc__D_e, EX_gln__L_e, EX_gly_e, EX_h_e, EX_h2o_e, EX_ile__L_e, EX_k_e, EX_leu__L_e, EX_lys__L_e, EX_na1_e, EX_nh4_e, EX_o2_e, EX_phe__L_e, EX_pi_e, EX_pro__L_e, EX_ser__L_e, EX_thr__L_e, EX_trp__L_e, EX_tyr__L_e, EX_val__L_e'''
except_EX_names_split = except_EX_names.split(', ')
print except_EX_names_split

# Changing all lower bounds to 0 except the given reactions above

for a in model.reactions[1188:1591]:
    a.lower_bound = 0

for b in model.reactions[1188:1591]:
    for c in range(len(except_EX_names_split)):  
        if b.id  == except_EX_names_split[c]:
            b.lower_bound = -1
            
biomass_NCI60 = Reaction('biomass_NCI60')
biomass_NCI60.name = biomass_NCI60

ala_L_c = model.metabolites.get_by_id('ala__L_c')
arg_L_c = model.metabolites.get_by_id('arg__L_c')
asn_L_c = model.metabolites.get_by_id('asn__L_c')
asp_L_c = model.metabolites.get_by_id('asp__L_c')
atp_c = model.metabolites.get_by_id('atp_c')
clpn_hs_c = model.metabolites.get_by_id('clpn_hs_c')
ctp_c = model.metabolites.get_by_id('ctp_c')
dag_hs_c = model.metabolites.get_by_id('dag_hs_c')
datp_c = model.metabolites.get_by_id('datp_c')
dctp_c = model.metabolites.get_by_id('dctp_c')
dgtp_c = model.metabolites.get_by_id('dgtp_c')
dttp_c = model.metabolites.get_by_id('dttp_c')
gln_L_c = model.metabolites.get_by_id('gln__L_c')
glu_L_c = model.metabolites.get_by_id('glu__L_c')
gly_c = model.metabolites.get_by_id('gly_c')
glygn2_c = model.metabolites.get_by_id('glygn2_c')
gtp_c = model.metabolites.get_by_id('gtp_c')
h2o_c = model.metabolites.get_by_id('h2o_c')
hdca_c = model.metabolites.get_by_id('hdca_c')
hdcea_c = model.metabolites.get_by_id('hdcea_c')
ile_L_c = model.metabolites.get_by_id('ile__L_c')
leu_L_c = model.metabolites.get_by_id('leu__L_c')
lpchol_hs_c = model.metabolites.get_by_id('lpchol_hs_c')
lys_L_c = model.metabolites.get_by_id('lys__L_c')
mag_hs_c = model.metabolites.get_by_id('mag_hs_c')
ocdca_c = model.metabolites.get_by_id('ocdca_c')
ocdcea_c = model.metabolites.get_by_id('ocdcea_c')
pa_hs_c = model.metabolites.get_by_id('pa_hs_c')
pail_hs_c = model.metabolites.get_by_id('pail_hs_c')
pchol_hs_c = model.metabolites.get_by_id('pchol_hs_c')
pe_hs_c = model.metabolites.get_by_id('pe_hs_c')
phe_L_c = model.metabolites.get_by_id('phe__L_c')
ps_hs_c = model.metabolites.get_by_id('ps_hs_c')
ser_L_c = model.metabolites.get_by_id('ser__L_c')
sphmyln_hs_c = model.metabolites.get_by_id('sphmyln_hs_c')
thr_L_c = model.metabolites.get_by_id('thr__L_c')
trp_L_c = model.metabolites.get_by_id('trp__L_c')
tyr_L_c = model.metabolites.get_by_id('tyr__L_c')
utp_c = model.metabolites.get_by_id('utp_c')
val_L_c = model.metabolites.get_by_id('val__L_c')
pro_L_m = model.metabolites.get_by_id('pro__L_m')
chsterol_r = model.metabolites.get_by_id('chsterol_r')
xolest_hs_r = model.metabolites.get_by_id('xolest_hs_r')
adp_c = model.metabolites.get_by_id('adp_c')
h_c = model.metabolites.get_by_id('h_c')
pi_c = model.metabolites.get_by_id('pi_c')

#remove ocdca and ocdcea
# added xolest value to cholesterol in biomass and remove xolest

biomass_NCI60.add_metabolites({ala_L_c: -0.587929, arg_L_c: -0.380280, asn_L_c: -0.323313, asp_L_c: -0.261396, 
                               atp_c: -35.033540, clpn_hs_c: -0.000624, ctp_c: -0.033435, dag_hs_c: -0.001032, 
                               datp_c: -0.014557, dctp_c: -0.009770, dgtp_c: -0.009748, dttp_c: -0.014546,
                               gln_L_c: -0.319051, glu_L_c: -0.387401, gly_c: -0.504294, glygn2_c: -0.034479,
                               gtp_c: -0.055967, h2o_c: -35.000000, hdca_c: -0.008293, hdcea_c: -0.003315, 
                               ile_L_c: -0.319813, leu_L_c: -0.548692, lpchol_hs_c: -0.002470, lys_L_c: -0.552717, 
                               mag_hs_c: -0.001456, pa_hs_c: -0.010645,
                               pail_hs_c: -0.005016, pchol_hs_c: -0.022878, pe_hs_c: -0.018211, phe_L_c: -0.170743,
                               ps_hs_c: -0.006808, ser_L_c: -0.385852, sphmyln_hs_c: -0.010215, thr_L_c: -0.378004, 
                               trp_L_c: -0.039847, tyr_L_c: -0.150141, utp_c: -0.063323, val_L_c: -0.385554,
                               pro_L_m: -0.237850, chsterol_r: -0.054102,  adp_c: 35.000000, 
                               h_c: 35.000000, pi_c: 35.000000})

model.add_reaction(biomass_NCI60)
my_objective = model.reactions.get_by_id('biomass_NCI60')
model.change_objective(my_objective)

# setting arginine uptake to 0

model.reactions[model.reactions.index('EX_arg__L_e')].lower_bound = 0

from cobra.flux_analysis.parsimonious import optimize_minimal_flux
solution = cobra.flux_analysis.parsimonious.optimize_minimal_flux(model)

['DM_etha_c', 'EX_peplys_e', 'EX_Tyr_ggn_e', 'EX_arg__L_e', 'EX_asn__L_e', 'EX_asp__L_e', 'EX_chol_e', 'EX_cl_e', 'EX_glc__D_e', 'EX_gln__L_e', 'EX_gly_e', 'EX_h_e', 'EX_h2o_e', 'EX_ile__L_e', 'EX_k_e', 'EX_leu__L_e', 'EX_lys__L_e', 'EX_na1_e', 'EX_nh4_e', 'EX_o2_e', 'EX_phe__L_e', 'EX_pi_e', 'EX_pro__L_e', 'EX_ser__L_e', 'EX_thr__L_e', 'EX_trp__L_e', 'EX_tyr__L_e', 'EX_val__L_e']


In [3]:
# rxn_name = raw_input('What reactions would you like to build the kinetic model with?   ')
# hard coded the rxns for this example so it's easier to run
rxn_name = 'ARGSS, ARGSL, CITRtm, OCBTm, PRASCSi'
#CITRtm?

In [4]:
v_matrix = [0]*32

In [5]:
#rxn_name = raw_input("What are the names of your reactions:   ")

rxns = rxn_name.split(', ')
print rxns

['ARGSS', 'ARGSL', 'CITRtm', 'OCBTm', 'PRASCSi']


In [6]:
print model.solution.x_dict['ARGSS']
print model.solution.x_dict['ARGSL']
print model.solution.x_dict['CITRtm']
print model.solution.x_dict['OCBTm']
print model.solution.x_dict['PRASCSi']

0.486198921177
0.486198921177
0.486198921177
0.486198921177
0.145511916527


In [7]:
v_count = 0
for c in rxns:
    v_matrix[v_count] = np.sign(model.solution.x_dict[c])
    v_count = v_count + 1

v_array = np.asarray(v_matrix)
v_diag = np.diag(v_array)
v_diag.shape
#print v_diag

new_v_diag = np.delete(v_diag, np.s_[len(rxns):], axis =1)
#print new_v_diag
new_new_v_diag = np.delete(new_v_diag, np.s_[len(rxns):], axis = 0)
print new_new_v_diag
# new_v_diag is our sign(v)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [8]:
import csv
cr = csv.reader(open("ARGSS_S_matrix_6.csv","rb"))
arr = range(32) #adjust to needed
x = 0
for row in cr:    
    arr[x] = row
    x += 1

#print arr
# arr is our S for the subnetwork

S = np.asarray(arr)
S_num = np.array(S, np.float)
print S_num
print S_num.shape

[[ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 1. -1.  0.  0.  0.]
 [-1.  0.  0.  0. -1.]
 [-1.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-1.  0.  0.  1.  0.]
 [ 0.  0.  1. -1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.]]
(32, 5)


In [9]:
sign_v_S = np.dot(new_new_v_diag, np.transpose(S_num))
print sign_v_S
# sign_v_S is our S normalized to v

#sign_v_S_T = np.transpose(sign_v_S)
# sign_v_S_T is our sign(v)S^T array

print sign_v_S.shape

[[ 0.  0.  1.  0.  1. -1. -1.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  1.  0.  0.  0.  0.  0.  0.
   0.  0.  0. -1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0. -1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  1.  1.]]
(5, 32)


In [10]:
Keqs = [0.501, 0.0065, 120000, 1, 160000000000]

In [11]:
lnKeqs = [0] * len(Keqs)
Keq_counter = 0
for d in Keqs:
    if d == 0:
        lnKeqs[Keq_counter] = 0
    else:
        lnKeqs[Keq_counter] = math.log(d)
        Keq_counter = Keq_counter + 1
        #print d
        
lnKeqs_array = np.asarray(lnKeqs)
print lnKeqs_array

[ -0.69114918  -5.0359531   11.69524702   0.          25.79843965]


In [12]:
# setting bounds
y_bounds = (-20,0)

In [13]:
c = random.uniform(-1,1)
print c
c_array = [c]*32
print c_array

-0.53448355923
[-0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697, -0.5344835592296697]


* v_diag is our sign(v)
* sign_v_Sis our sign(v) S^T array
* lnKeqs_array is an array of our ln(Keqs)
* y_bounds is our bound
* c_array is an array of a random float generated between -1 and 1

In [14]:
from scipy.optimize import linprog
res = linprog(c_array, A_ub = sign_v_S, b_ub = lnKeqs_array, bounds= y_bounds, options=dict(bland=True))

In [15]:
res

  status: 0
   slack: array([  0.        ,  11.69524702,   0.        ,  25.79843965,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   5.0359531 ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.69114918,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,   0.        ])
 success: True
     fun: 3.0610420106750098
       x: array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        , -5.0359531 ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        , -0.69114

In [16]:
res.x

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        , -5.0359531 ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        , -0.69114918,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ])

### Takes e^(metabolite conc) output from linprog array

In [17]:
met_samp_conc = [0] * len(res.x)
for i in range(len(res.x)):
    met_samp_conc[i] = math.exp(res.x[i])

### Sampled met concentrations

In [18]:
met_samp_conc

[1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.006499999999999998,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.5009999999999996,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0]